pdf: milestone02.md
	pandoc milestone02.md -o milestone02.pdf \
	--metadata date="`date +'%d %B %Y'`" \
	--citeproc \
	--csl=bib/acm-sig-proceedings-long-author-list.csl \
	--bibliography=bib/milestone01.bib \
	-N\
	-toc \
	--toc-depth=2

# csl styles: https://www.zotero.org/styles?fields=engineering&format=numeric&dependent=0
# --csl=acta-polytechnica.csl \

