pdf: milestone01.md
	pandoc milestone01.md -o milestone01.pdf \
	--metadata date="`date +'%d %B %Y'`" \
	--citeproc \
	--csl=acm-sig-proceedings-long-author-list.csl \
	--bibliography=milestone01.bib \
	-N

# csl styles: https://www.zotero.org/styles?fields=engineering&format=numeric&dependent=0
# --csl=acta-polytechnica.csl \

